baseURL:
  "https://blog.tommylin.tech/"

languageCode:
  "en-us"

title:
  "Tommy's Blog"

theme:
  "PaperMod"

hasCJKLanguage: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

Params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Welcome to Tommy's blog, documenting my journey in backend development, Golang, machine learning, and in-depth book reviews."
  keywords: [Tommy, Blog, Golang, Backend, Devops, technical, computer science, AWS]
  defaultTheme: dark
  author: Tommy Lin
  displayFullLangName: true
  images: ["android-chrome-512x512.png"]
  DateFormat: "January 2, 2006"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  ShowWordCount: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  tocopen: false

  # profile-mode
  profileMode:
    enabled: true
    title: "Tommy's Blog"
    subtitle: "Welcome to Tommy's blog, documenting my journey in backend development, Golang, machine learning, and in-depth book reviews."
    imageUrl: "scared_seal.jpeg"
    imageTitle: "<title of image as alt>"
    imageWidth: 120
    imageHeight: 120
    buttons:
        - name: Archive
          url: archives
        - name: Tags
          url: tags
        - name: Search
          url: search

  # home-info mode
  homeInfoParams:
    Title: "Tommy's Blog"
    Content: >
      記錄一波！

  socialIcons:
    - name: github
      url: "https://github.com/TommyLin81"
    - name: linkedin
      url: "https://www.linkedin.com/in/%E5%A8%81%E5%84%92-%E6%9E%97-0389351a4/"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "content", "description"]

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Archive
      url: archives
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
    - name: Categories
      url: categories/
      weight: 3
    - name: Search
      url: search/
      weight: 10

taxonomies:
  category: categories
  tag: tags

privacy:
    vimeo:
        disabled: false
        simple: true
    twitter:
        disabled: false
        enableDNT: true
        simple: true
    instagram:
        disabled: false
        simple: true
    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
